<a href="https://colab.research.google.com/github/Mahian-Hoq/ml-notebooks-from-scratch/blob/main/Understanding_Pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Understanding The basic of Pipeline

Here I have tried to use basic pipeline, how to use it, what can I do with it. These informations are learned and practice here.

In future we will see more of the pipeline use

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

Here We will create a ultimate pipeling For heart data. For the dataset visit here:

https://www.kaggle.com/datasets/fedesoriano/heart-failure-prediction?resource=download

In [ ]:
from google.colab import files
files.upload()

Saving heart.csv to heart.csv

{'heart.csv': b'Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease\n40,M,ATA,140,289,0,Normal,172,N,0,Up,0\n49,F,NAP,160,180,0,Normal,156,N,1,Flat,1\n37,M,ATA,130,283,0,ST,98,N,0,Up,0\n48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1\n54,M,NAP,150,195,0,Normal,122,N,0,Up,0\n39,M,NAP,120,339,0,Normal,170,N,0,Up,0\n45,F,ATA,130,237,0,Normal,170,N,0,Up,0\n54,M,ATA,110,208,0,Normal,142,N,0,Up,0\n37,M,ASY,140,207,0,Normal,130,Y,1.5,Flat,1\n48,F,ATA,120,284,0,Normal,120,N,0,Up,0\n37,F,NAP,130,211,0,Normal,142,N,0,Up,0\n58,M,ATA,136,164,0,ST,99,Y,2,Flat,1\n39,M,ATA,120,204,0,Normal,145,N,0,Up,0\n49,M,ASY,140,234,0,Normal,140,Y,1,Flat,1\n42,F,NAP,115,211,0,ST,137,N,0,Up,0\n54,F,ATA,120,273,0,Normal,150,N,1.5,Flat,0\n38,M,ASY,110,196,0,Normal,166,N,0,Flat,1\n43,F,ATA,120,201,0,Normal,165,N,0,Up,0\n60,M,ASY,100,248,0,Normal,125,N,1,Flat,1\n36,M,ATA,120,267,0,Normal,160,N,3,Flat,1\n43,F,TA,100,223,0,Normal,142,N,0,Up,0\n44,M,ATA,120,184,0,Normal,142,N,1,Flat,0\n49,F,ATA,124,201,0,Normal,164,N,0,Up,0\n44,M,ATA,150,288,0,Normal,150,Y,3,Flat,1\n40,M,NAP,130,215,0,Normal,138,N,0,Up,0\n36,M,NAP,130,209,0,Normal,178,N,0,Up,0\n53,M,ASY,124,260,0,ST,112,Y,3,Flat,0\n52,M,ATA,120,284,0,Normal,118,N,0,Up,0\n53,F,ATA,113,468,0,Normal,127,N,0,Up,0\n51,M,ATA,125,188,0,Normal,145,N,0,Up,0\n53,M,NAP,145,518,0,Normal,130,N,0,Flat,1\n56,M,NAP,130,167,0,Normal,114,N,0,Up,0\n54,M,ASY,125,224,0,Normal,122,N,2,Flat,1\n41,M,ASY,130,172,0,ST,130,N,2,Flat,1\n43,F,ATA,150,186,0,Normal,154,N,0,Up,0\n32,M,ATA,125,254,0,Normal,155,N,0,Up,0\n65,M,ASY,140,306,1,Normal,87,Y,1.5,Flat,1\n41,F,ATA,110,250,0,ST,142,N,0,Up,0\n48,F,ATA,120,177,1,ST,148,N,0,Up,0\n48,F,ASY,150,227,0,Normal,130,Y,1,Flat,0\n54,F,ATA,150,230,0,Normal,130,N,0,Up,0\n54,F,NAP,130,294,0,ST,100,Y,0,Flat,1\n35,M,ATA,150,264,0,Normal,168,N,0,Up,0\n52,M,NAP,140,259,0,ST,170,N,0,Up,0\n43,M,ASY,120,175,0,Normal,120,Y,1,Flat,1\n59,M,NAP,130,318,0,Normal,120,Y,1,Flat,0\n37,M,ASY,120,223,0,Normal,168,N,0,Up,0\n50,M,ATA,140,216,0,Normal,170,N,0,Up,0\n36,M,NAP,112,340,0,Normal,184,N,1,Flat,0\n41,M,ASY,110,289,0,Normal,170,N,0,Flat,1\n50,M,ASY,130,233,0,Normal,121,Y,2,Flat,1\n47,F,ASY,120,205,0,Normal,98,Y,2,Flat,1\n45,M,ATA,140,224,1,Normal,122,N,0,Up,0\n41,F,ATA,130,245,0,Normal,150,N,0,Up,0\n52,F,ASY,130,180,0,Normal,140,Y,1.5,Flat,0\n51,F,ATA,160,194,0,Normal,170,N,0,Up,0\n31,M,ASY,120,270,0,Normal,153,Y,1.5,Flat,1\n58,M,NAP,130,213,0,ST,140,N,0,Flat,1\n54,M,ASY,150,365,0,ST,134,N,1,Up,0\n52,M,ASY,112,342,0,ST,96,Y,1,Flat,1\n49,M,ATA,100,253,0,Normal,174,N,0,Up,0\n43,F,NAP,150,254,0,Normal,175,N,0,Up,0\n45,M,ASY,140,224,0,Normal,144,N,0,Up,0\n46,M,ASY,120,277,0,Normal,125,Y,1,Flat,1\n50,F,ATA,110,202,0,Normal,145,N,0,Up,0\n37,F,ATA,120,260,0,Normal,130,N,0,Up,0\n45,F,ASY,132,297,0,Normal,144,N,0,Up,0\n32,M,ATA,110,225,0,Normal,184,N,0,Up,0\n52,M,ASY,160,246,0,ST,82,Y,4,Flat,1\n44,M,ASY,150,412,0,Normal,170,N,0,Up,0\n57,M,ATA,140,265,0,ST,145,Y,1,Flat,1\n44,M,ATA,130,215,0,Normal,135,N,0,Up,0\n52,M,ASY,120,182,0,Normal,150,N,0,Flat,1\n44,F,ASY,120,218,0,ST,115,N,0,Up,0\n55,M,ASY,140,268,0,Normal,128,Y,1.5,Flat,1\n46,M,NAP,150,163,0,Normal,116,N,0,Up,0\n32,M,ASY,118,529,0,Normal,130,N,0,Flat,1\n35,F,ASY,140,167,0,Normal,150,N,0,Up,0\n52,M,ATA,140,100,0,Normal,138,Y,0,Up,0\n49,M,ASY,130,206,0,Normal,170,N,0,Flat,1\n55,M,NAP,110,277,0,Normal,160,N,0,Up,0\n54,M,ATA,120,238,0,Normal,154,N,0,Up,0\n63,M,ASY,150,223,0,Normal,115,N,0,Flat,1\n52,M,ATA,160,196,0,Normal,165,N,0,Up,0\n56,M,ASY,150,213,1,Normal,125,Y,1,Flat,1\n66,M,ASY,140,139,0,Normal,94,Y,1,Flat,1\n65,M,ASY,170,263,1,Normal,112,Y,2,Flat,1\n53,F,ATA,140,216,0,Normal,142,Y,2,Flat,0\n43,M,TA,120,291,0,ST,155,N,0,Flat,1\n55,M,ASY,140,229,0,Normal,110,Y,0.5,Flat,0\n49,F,ATA,110,208,0,Normal,160,N,0,Up,0\n39,M,ASY,130,307,0,Normal,140,N,0,Up,0\n52,F,ATA,120,210,0,Normal,148,N,0,Up,0\n48,M,ASY,160,329,0,Normal,92,Y,1.5,Flat,1\n39,F,NAP,110,182,0,ST,180,N,0,Up,0\n58,M,ASY,130,263,0,Normal,140,Y,2,Flat,1\n43,M,ATA,142,207,0,Normal,138,N,0,Up,0\n39,M,NAP,160,147,1,Normal,160,N,0,Up,0\n56,M,ASY,120,85,0,Normal,140,N,0,Up,0\n41,M,ATA,125,269,0,Normal,144,N,0,Up,0\n65,M,ASY,130,275,0,ST,115,Y,1,Flat,1\n51,M,ASY,130,179,0,Normal,100,N,0,Up,0\n40,F,ASY,150,392,0,Normal,130,N,2,Flat,1\n40,M,ASY,120,466,1,Normal,152,Y,1,Flat,1\n46,M,ASY,118,186,0,Normal,124,N,0,Flat,1\n57,M,ATA,140,260,1,Normal,140,N,0,Up,0\n48,F,ASY,120,254,0,ST,110,N,0,Up,0\n34,M,ATA,150,214,0,ST,168,N,0,Up,0\n50,M,ASY,140,129,0,Normal,135,N,0,Up,0\n39,M,ATA,190,241,0,Normal,106,N,0,Up,0\n59,F,ATA,130,188,0,Normal,124,N,1,Flat,0\n57,M,ASY,150,255,0,Normal,92,Y,3,Flat,1\n47,M,ASY,140,276,1,Normal,125,Y,0,Up,0\n38,M,ATA,140,297,0,Normal,150,N,0,Up,0\n49,F,NAP,130,207,0,ST,135,N,0,Up,0\n33,F,ASY,100,246,0,Normal,150,Y,1,Flat,1\n38,M,ASY,120,282,0,Normal,170,N,0,Flat,1\n59,F,ASY,130,338,1,ST,130,Y,1.5,Flat,1\n35,F,TA,120,160,0,ST,185,N,0,Up,0\n34,M,TA,140,156,0,Normal,180,N,0,Flat,1\n47,F,NAP,135,248,1,Normal,170,N,0,Flat,1\n52,F,NAP,125,272,0,Normal,139,N,0,Up,0\n46,M,ASY,110,240,0,ST,140,N,0,Up,0\n58,F,ATA,180,393,0,Normal,110,Y,1,Flat,1\n58,M,ATA,130,230,0,Normal,150,N,0,Up,0\n54,M,ATA,120,246,0,Normal,110,N,0,Up,0\n34,F,ATA,130,161,0,Normal,190,N,0,Up,0\n48,F,ASY,108,163,0,Normal,175,N,2,Up,0\n54,F,ATA,120,230,1,Normal,140,N,0,Up,0\n42,M,NAP,120,228,0,Normal,152,Y,1.5,Flat,0\n38,M,NAP,145,292,0,Normal,130,N,0,Up,0\n46,M,ASY,110,202,0,Normal,150,Y,0,Flat,1\n56,M,ASY,170,388,0,ST,122,Y,2,Flat,1\n56,M,ASY,150,230,0,ST,124,Y,1.5,Flat,1\n61,F,ASY,130,294,0,ST,120,Y,1,Flat,0\n49,M,NAP,115,265,0,Normal,175,N,0,Flat,1\n43,F,ATA,120,215,0,ST,175,N,0,Up,0\n39,M,ATA,120,241,0,ST,146,N,2,Up,0\n54,M,ASY,140,166,0,Normal,118,Y,0,Flat,1\n43,M,ASY,150,247,0,Normal,130,Y,2,Flat,1\n52,M,ASY,160,331,0,Normal,94,Y,2.5,Flat,1\n50,M,ASY,140,341,0,ST,125,Y,2.5,Flat,1\n47,M,ASY,160,291,0,ST,158,Y,3,Flat,1\n53,M,ASY,140,243,0,Normal,155,N,0,Up,0\n56,F,ATA,120,279,0,Normal,150,N,1,Flat,1\n39,M,ASY,110,273,0,Normal,132,N,0,Up,0\n42,M,ATA,120,198,0,Normal,155,N,0,Up,0\n43,F,ATA,120,249,0,ST,176,N,0,Up,0\n50,M,ATA,120,168,0,Normal,160,N,0,Up,0\n54,M,ASY,130,603,1,Normal,125,Y,1,Flat,1\n39,M,ATA,130,215,0,Normal,120,N,0,Up,0\n48,M,ATA,100,159,0,Normal,100,N,0,Up,0\n40,M,ATA,130,275,0,Normal,150,N,0,Up,0\n55,M,ASY,120,270,0,Normal,140,N,0,Up,0\n41,M,ATA,120,291,0,ST,160,N,0,Up,0\n56,M,ASY,155,342,1,Normal,150,Y,3,Flat,1\n38,M,ASY,110,190,0,Normal,150,Y,1,Flat,1\n49,M,ASY,140,185,0,Normal,130,N,0,Up,0\n44,M,ASY,130,290,0,Normal,100,Y,2,Flat,1\n54,M,ATA,160,195,0,ST,130,N,1,Up,0\n59,M,ASY,140,264,1,LVH,119,Y,0,Flat,1\n49,M,ASY,128,212,0,Normal,96,Y,0,Flat,1\n47,M,ATA,160,263,0,Normal,174,N,0,Up,0\n42,M,ATA,120,196,0,Normal,150,N,0,Up,0\n52,F,ATA,140,225,0,Normal,140,N,0,Up,0\n46,M,TA,140,272,1,Normal,175,N,2,Flat,1\n50,M,ASY,140,231,0,ST,140,Y,5,Flat,1\n48,M,ATA,140,238,0,Normal,118,N,0,Up,0\n58,M,ASY,135,222,0,Normal,100,N,0,Up,0\n58,M,NAP,140,179,0,Normal,160,N,0,Up,0\n29,M,ATA,120,243,0,Normal,160,N,0,Up,0\n40,M,NAP,140,235,0,Normal,188,N,0,Up,0\n53,M,ATA,140,320,0,Normal,162,N,0,Up,0\n49,M,NAP,140,187,0,Normal,172,N,0,Up,0\n52,M,ASY,140,266,0,Normal,134,Y,2,Flat,1\n43,M,ASY,140,288,0,Normal,135,Y,2,Flat,1\n54,M,ASY,140,216,0,Normal,105,N,1.5,Flat,1\n59,M,ATA,140,287,0,Normal,150,N,0,Up,0\n37,M,NAP,130,194,0,Normal,150,N,0,Up,0\n46,F,ASY,130,238,0,Normal,90,N,0,Up,0\n52,M,ASY,130,225,0,Normal,120,Y,2,Flat,1\n51,M,ATA,130,224,0,Normal,150,N,0,Up,0\n52,M,ASY,140,404,0,Normal,124,Y,2,Flat,1\n46,M,ASY,110,238,0,ST,140,Y,1,Flat,0\n54,F,ATA,160,312,0,Normal,130,N,0,Up,0\n58,M,NAP,160,211,1,ST,92,N,0,Flat,1\n58,M,ATA,130,251,0,Normal,110,N,0,Up,0\n41,M,ASY,120,237,1,Normal,138,Y,1,Flat,1\n50,F,ASY,120,328,0,Normal,110,Y,1,Flat,0\n53,M,ASY,180,285,0,ST,120,Y,1.5,Flat,1\n46,M,ASY,180,280,0,ST,120,N,0,Up,0\n50,M,ATA,170,209,0,ST,116,N,0,Up,0\n48,M,ATA,130,245,0,Normal,160,N,0,Up,0\n45,M,NAP,135,192,0,Normal,110,N,0,Up,0\n41,F,ATA,125,184,0,Normal,180,N,0,Up,0\n62,F,TA,160,193,0,Normal,116,N,0,Up,0\n49,M,ASY,120,297,0,Normal,132,N,1,Flat,0\n42,M,ATA,150,268,0,Normal,136,N,0,Up,0\n53,M,ASY,120,246,0,Normal,116,Y,0,Flat,1\n57,F,TA,130,308,0,Normal,98,N,1,Flat,0\n47,M,TA,110,249,0,Normal,150,N,0,Up,0\n46,M,NAP,120,230,0,Normal,150,N,0,Up,0\n42,M,NAP,160,147,0,Normal,146,N,0,Up,0\n31,F,ATA,100,219,0,ST,150,N,0,Up,0\n56,M,ATA,130,184,0,Normal,100,N,0,Up,0\n50,M,ASY,150,215,0,Normal,140,Y,0,Up,0\n35,M,ATA,120,308,0,LVH,180,N,0,Up,0\n35,M,ATA,110,257,0,Normal,140,N,0,Flat,1\n28,M,ATA,130,132,0,LVH,185,N,0,Up,0\n54,M,ASY,125,216,0,Normal,140,N,0,Flat,1\n48,M,ASY,106,263,1,Normal,110,N,0,Flat,1\n50,F,NAP,140,288,0,Normal,140,Y,0,Flat,1\n56,M,NAP,130,276,0,Normal,128,Y,1,Up,0\n56,F,NAP,130,219,0,ST,164,N,0,Up,0\n47,M,ASY,150,226,0,Normal,98,Y,1.5,Flat,1\n30,F,TA,170,237,0,ST,170,N,0,Up,0\n39,M,ASY,110,280,0,Normal,150,N,0,Flat,1\n54,M,NAP,120,217,0,Normal,137,N,0,Up,0\n55,M,ATA,140,196,0,Normal,150,N,0,Up,0\n29,M,ATA,140,263,0,Normal,170,N,0,Up,0\n46,M,ASY,130,222,0,Normal,112,N,0,Flat,1\n51,F,ASY,160,303,0,Normal,150,Y,1,Flat,1\n48,F,NAP,120,195,0,Normal,125,N,0,Up,0\n33,M,NAP,120,298,0,Normal,185,N,0,Up,0\n55,M,ATA,120,256,1,Normal,137,N,0,Up,0\n50,M,ASY,145,264,0,Normal,150,N,0,Flat,1\n53,M,NAP,120,195,0,Normal,140,N,0,Up,0\n38,M,ASY,92,117,0,Normal,134,Y,2.5,Flat,1\n41,M,ATA,120,295,0,Normal,170,N,0,Up,0\n37,F,ASY,130,173,0,ST,184,N,0,Up,0\n37,M,ASY,130,315,0,Normal,158,N,0,Up,0\n40,M,NAP,130,281,0,Normal,167,N,0,Up,0\n38,F,ATA,120,275,0,Normal,129,N,0,Up,0\n41,M,ASY,112,250,0,Normal,142,N,0,Up,0\n54,F,ATA,140,309,0,ST,140,N,0,Up,0\n39,M,ATA,120,200,0,Normal,160,Y,1,Flat,0\n41,M,ASY,120,336,0,Normal,118,Y,3,Flat,1\n55,M,TA,140,295,0,Normal,136,N,0,Flat,1\n48,M,ASY,160,355,0,Normal,99,Y,2,Flat,1\n48,M,ASY,160,193,0,Normal,102,Y,3,Flat,1\n55,M,ATA,145,326,0,Normal,155,N,0,Up,0\n54,M,ASY,200,198,0,Normal,142,Y,2,Flat,1\n55,M,ATA,160,292,1,Normal,143,Y,2,Flat,1\n43,F,ATA,120,266,0,Normal,118,N,0,Up,0\n48,M,ASY,160,268,0,Normal,103,Y,1,Flat,1\n54,M,TA,120,171,0,Normal,137,N,2,Up,0\n54,M,NAP,120,237,0,Normal,150,Y,1.5,Flat,1\n48,M,ASY,122,275,1,ST,150,Y,2,Down,1\n45,M,ASY,130,219,0,ST,130,Y,1,Flat,1\n49,M,ASY,130,341,0,Normal,120,Y,1,Flat,1\n44,M,ASY,135,491,0,Normal,135,N,0,Flat,1\n48,M,ASY,120,260,0,Normal,115,N,2,Flat,1\n61,M,ASY,125,292,0,ST,115,Y,0,Up,0\n62,M,ATA,140,271,0,Normal,152,N,1,Up,0\n55,M,ASY,145,248,0,Normal,96,Y,2,Flat,1\n53,F,NAP,120,274,0,Normal,130,N,0,Up,0\n55,F,ATA,130,394,0,LVH,150,N,0,Up,0\n36,M,NAP,150,160,0,Normal,172,N,0,Up,0\n51,F,NAP,150,200,0,Normal,120,N,0.5,Up,0\n55,F,ATA,122,320,0,Normal,155,N,0,Up,0\n46,M,ATA,140,275,0,Normal,165,Y,0,Up,0\n54,F,ATA,120,221,0,Normal,138,N,1,Up,0\n46,M,ASY,120,231,0,Normal,115,Y,0,Flat,1\n59,M,ASY,130,126,0,Normal,125,N,0,Flat,1\n47,M,NAP,140,193,0,Normal,145,Y,1,Flat,1\n54,M,ATA,160,305,0,Normal,175,N,0,Up,0\n52,M,ASY,130,298,0,Normal,110,Y,1,Flat,1\n34,M,ATA,98,220,0,Normal,150,N,0,Up,0\n54,M,ASY,130,242,0,Normal,91,Y,1,Flat,1\n47,F,NAP,130,235,0,Normal,145,N,2,Flat,0\n45,M,ASY,120,225,0,Normal,140,N,0,Up,0\n32,F,ATA,105,198,0,Normal,165,N,0,Up,0\n55,M,ASY,140,201,0,Normal,130,Y,3,Flat,1\n55,M,NAP,120,220,0,LVH,134,N,0,Up,0\n45,F,ATA,180,295,0,Normal,180,N,0,Up,0\n59,M,NAP,180,213,0,Normal,100,N,0,Up,0\n51,M,NAP,135,160,0,Normal,150,N,2,Flat,1\n52,M,ASY,170,223,0,Normal,126,Y,1.5,Flat,1\n57,F,ASY,180,347,0,ST,126,Y,0.8,Flat,0\n54,F,ATA,130,253,0,ST,155,N,0,Up,0\n60,M,NAP,120,246,0,LVH,135,N,0,Up,0\n49,M,ASY,150,222,0,Normal,122,N,2,Flat,1\n51,F,NAP,130,220,0,Normal,160,Y,2,Up,0\n55,F,ATA,110,344,0,ST,160,N,0,Up,0\n42,M,ASY,140,358,0,Normal,170,N,0,Up,0\n51,F,NAP,110,190,0,Normal,120,N,0,Up,0\n59,M,ASY,140,169,0,Normal,140,N,0,Up,0\n53,M,ATA,120,181,0,Normal,132,N,0,Up,0\n48,F,ATA,133,308,0,ST,156,N,2,Up,0\n36,M,ATA,120,166,0,Normal,180,N,0,Up,0\n48,M,NAP,110,211,0,Normal,138,N,0,Up,0\n47,F,ATA,140,257,0,Normal,135,N,1,Up,0\n53,M,ASY,130,182,0,Normal,148,N,0,Up,0\n65,M,ASY,115,0,0,Normal,93,Y,0,Flat,1\n32,M,TA,95,0,1,Normal,127,N,0.7,Up,1\n61,M,ASY,105,0,1,Normal,110,Y,1.5,Up,1\n50,M,ASY,145,0,1,Normal,139,Y,0.7,Flat,1\n57,M,ASY,110,0,1,ST,131,Y,1.4,Up,1\n51,M,ASY,110,0,1,Normal,92,N,0,Flat,1\n47,M,ASY,110,0,1,ST,149,N,2.1,Up,1\n60,M,ASY,160,0,1,Normal,149,N,0.4,Flat,1\n55,M,ATA,140,0,0,ST,150,N,0.2,Up,0\n53,M,ASY,125,0,1,Normal,120,N,1.5,Up,1\n62,F,ASY,120,0,1,ST,123,Y,1.7,Down,1\n51,M,ASY,95,0,1,Normal,126,N,2.2,Flat,1\n51,F,ASY,120,0,1,Normal,127,Y,1.5,Up,1\n55,M,ASY,115,0,1,Normal,155,N,0.1,Flat,1\n53,M,ATA,130,0,0,ST,120,N,0.7,Down,0\n58,M,ASY,115,0,1,Normal,138,N,0.5,Up,1\n57,M,ASY,95,0,1,Normal,182,N,0.7,Down,1\n65,M,ASY,155,0,0,Normal,154,N,1,Up,0\n60,M,ASY,125,0,1,Normal,110,N,0.1,Up,1\n41,M,ASY,125,0,1,Normal,176,N,1.6,Up,1\n34,M,ASY,115,0,1,Normal,154,N,0.2,Up,1\n53,M,ASY,80,0,0,Normal,141,Y,2,Down,0\n74,M,ATA,145,0,1,ST,123,N,1.3,Up,1\n57,M,NAP,105,0,1,Normal,148,N,0.3,Flat,1\n56,M,ASY,140,0,1,Normal,121,Y,1.8,Up,1\n61,M,ASY,130,0,1,Normal,77,N,2.5,Flat,1\n68,M,ASY,145,0,1,Normal,136,N,1.8,Up,1\n59,M,NAP,125,0,1,Normal,175,N,2.6,Flat,1\n63,M,ASY,100,0,1,Normal,109,N,-0.9,Flat,1\n38,F,ASY,105,0,1,Normal,166,N,2.8,Up,1\n62,M,ASY,115,0,1,Normal,128,Y,2.5,Down,1\n46,M,ASY,100,0,1,ST,133,N,-2.6,Flat,1\n42,M,ASY,105,0,1,Normal,128,Y,-1.5,Down,1\n45,M,NAP,110,0,0,Normal,138,N,-0.1,Up,0\n59,M,ASY,125,0,1,Normal,119,Y,0.9,Up,1\n52,M,ASY,95,0,1,Normal,82,Y,0.8,Flat,1\n60,M,ASY,130,0,1,ST,130,Y,1.1,Down,1\n60,M,NAP,115,0,1,Normal,143,N,2.4,Up,1\n56,M,ASY,115,0,1,ST,82,N,-1,Up,1\n38,M,NAP,100,0,0,Normal,179,N,-1.1,Up,0\n40,M,ASY,95,0,1,ST,144,N,0,Up,1\n51,M,ASY,130,0,1,Normal,170,N,-0.7,Up,1\n62,M,TA,120,0,1,LVH,134,N,-0.8,Flat,1\n72,M,NAP,160,0,0,LVH,114,N,1.6,Flat,0\n63,M,ASY,150,0,1,ST,154,N,3.7,Up,1\n63,M,ASY,140,0,1,LVH,149,N,2,Up,1\n64,F,ASY,95,0,1,Normal,145,N,1.1,Down,1\n43,M,ASY,100,0,1,Normal,122,N,1.5,Down,1\n64,M,ASY,110,0,1,Normal,114,Y,1.3,Down,1\n61,M,ASY,110,0,1,Normal,113,N,1.4,Flat,1\n52,M,ASY,130,0,1,Normal,120,N,0,Flat,1\n51,M,ASY,120,0,1,Normal,104,N,0,Flat,1\n69,M,ASY,135,0,0,Normal,130,N,0,Flat,1\n59,M,ASY,120,0,0,Normal,115,N,0,Flat,1\n48,M,ASY,115,0,1,Normal,128,N,0,Flat,1\n69,M,ASY,137,0,0,ST,104,Y,1.6,Flat,1\n36,M,ASY,110,0,1,Normal,125,Y,1,Flat,1\n53,M,ASY,120,0,1,Normal,120,N,0,Flat,1\n43,M,ASY,140,0,0,ST,140,Y,0.5,Up,1\n56,M,ASY,120,0,0,ST,100,Y,-1,Down,1\n58,M,ASY,130,0,0,ST,100,Y,1,Flat,1\n55,M,ASY,120,0,0,ST,92,N,0.3,Up,1\n67,M,TA,145,0,0,LVH,125,N,0,Flat,1\n46,M,ASY,115,0,0,Normal,113,Y,1.5,Flat,1\n53,M,ATA,120,0,0,Normal,95,N,0,Flat,1\n38,M,NAP,115,0,0,Normal,128,Y,0,Flat,1\n53,M,NAP,105,0,0,Normal,115,N,0,Flat,1\n62,M,NAP,160,0,0,Normal,72,Y,0,Flat,1\n47,M,ASY,160,0,0,Normal,124,Y,0,Flat,1\n56,M,NAP,155,0,0,ST,99,N,0,Flat,1\n56,M,ASY,120,0,0,ST,148,N,0,Flat,1\n56,M,NAP,120,0,0,Normal,97,N,0,Flat,0\n64,F,ASY,200,0,0,Normal,140,Y,1,Flat,1\n61,M,ASY,150,0,0,Normal,117,Y,2,Flat,1\n68,M,ASY,135,0,0,ST,120,Y,0,Up,1\n57,M,ASY,140,0,0,Normal,120,Y,2,Flat,1\n63,M,ASY,150,0,0,Normal,86,Y,2,Flat,1\n60,M,ASY,135,0,0,Normal,63,Y,0.5,Up,1\n66,M,ASY,150,0,0,Normal,108,Y,2,Flat,1\n63,M,ASY,185,0,0,Normal,98,Y,0,Up,1\n59,M,ASY,135,0,0,Normal,115,Y,1,Flat,1\n61,M,ASY,125,0,0,Normal,105,Y,0,Down,1\n73,F,NAP,160,0,0,ST,121,N,0,Up,1\n47,M,NAP,155,0,0,Normal,118,Y,1,Flat,1\n65,M,ASY,160,0,1,ST,122,N,1.2,Flat,1\n70,M,ASY,140,0,1,Normal,157,Y,2,Flat,1\n50,M,ASY,120,0,0,ST,156,Y,0,Up,1\n60,M,ASY,160,0,0,ST,99,Y,0.5,Flat,1\n50,M,ASY,115,0,0,Normal,120,Y,0.5,Flat,1\n43,M,ASY,115,0,0,Normal,145,Y,2,Flat,1\n38,F,ASY,110,0,0,Normal,156,N,0,Flat,1\n54,M,ASY,120,0,0,Normal,155,N,0,Flat,1\n61,M,ASY,150,0,0,Normal,105,Y,0,Flat,1\n42,M,ASY,145,0,0,Normal,99,Y,0,Flat,1\n53,M,ASY,130,0,0,LVH,135,Y,1,Flat,1\n55,M,ASY,140,0,0,Normal,83,N,0,Flat,1\n61,M,ASY,160,0,1,ST,145,N,1,Flat,1\n51,M,ASY,140,0,0,Normal,60,N,0,Flat,1\n70,M,ASY,115,0,0,ST,92,Y,0,Flat,1\n61,M,ASY,130,0,0,LVH,115,N,0,Flat,1\n38,M,ASY,150,0,1,Normal,120,Y,0.7,Flat,1\n57,M,ASY,160,0,1,Normal,98,Y,2,Flat,1\n38,M,ASY,135,0,1,Normal,150,N,0,Flat,1\n62,F,TA,140,0,1,Normal,143,N,0,Flat,1\n58,M,ASY,170,0,1,ST,105,Y,0,Flat,1\n52,M,ASY,165,0,1,Normal,122,Y,1,Up,1\n61,M,NAP,200,0,1,ST,70,N,0,Flat,1\n50,F,ASY,160,0,1,Normal,110,N,0,Flat,1\n51,M,ASY,130,0,1,ST,163,N,0,Flat,1\n65,M,ASY,145,0,1,ST,67,N,0.7,Flat,1\n52,M,ASY,135,0,1,Normal,128,Y,2,Flat,1\n47,M,NAP,110,0,1,Normal,120,Y,0,Flat,1\n35,M,ASY,120,0,1,Normal,130,Y,1.2,Flat,1\n57,M,ASY,140,0,1,Normal,100,Y,0,Flat,1\n62,M,ASY,115,0,1,Normal,72,Y,-0.5,Flat,1\n59,M,ASY,110,0,1,Normal,94,N,0,Flat,1\n53,M,NAP,160,0,1,LVH,122,Y,0,Flat,1\n62,M,ASY,150,0,1,ST,78,N,2,Flat,1\n54,M,ASY,180,0,1,Normal,150,N,1.5,Flat,1\n56,M,ASY,125,0,1,Normal,103,Y,1,Flat,1\n56,M,NAP,125,0,1,Normal,98,N,-2,Flat,1\n54,M,ASY,130,0,1,Normal,110,Y,3,Flat,1\n66,F,ASY,155,0,1,Normal,90,N,0,Flat,1\n63,M,ASY,140,260,0,ST,112,Y,3,Flat,1\n44,M,ASY,130,209,0,ST,127,N,0,Up,0\n60,M,ASY,132,218,0,ST,140,Y,1.5,Down,1\n55,M,ASY,142,228,0,ST,149,Y,2.5,Up,1\n66,M,NAP,110,213,1,LVH,99,Y,1.3,Flat,0\n66,M,NAP,120,0,0,ST,120,N,-0.5,Up,0\n65,M,ASY,150,236,1,ST,105,Y,0,Flat,1\n60,M,NAP,180,0,0,ST,140,Y,1.5,Flat,0\n60,M,NAP,120,0,1,Normal,141,Y,2,Up,1\n60,M,ATA,160,267,1,ST,157,N,0.5,Flat,1\n56,M,ATA,126,166,0,ST,140,N,0,Up,0\n59,M,ASY,140,0,0,ST,117,Y,1,Flat,1\n62,M,ASY,110,0,0,Normal,120,Y,0.5,Flat,1\n63,M,NAP,133,0,0,LVH,120,Y,1,Flat,1\n57,M,ASY,128,0,1,ST,148,Y,1,Flat,1\n62,M,ASY,120,220,0,ST,86,N,0,Up,0\n63,M,ASY,170,177,0,Normal,84,Y,2.5,Down,1\n46,M,ASY,110,236,0,Normal,125,Y,2,Flat,1\n63,M,ASY,126,0,0,ST,120,N,1.5,Down,0\n60,M,ASY,152,0,0,ST,118,Y,0,Up,0\n58,M,ASY,116,0,0,Normal,124,N,1,Up,1\n64,M,ASY,120,0,1,ST,106,N,2,Flat,1\n63,M,NAP,130,0,0,ST,111,Y,0,Flat,1\n74,M,NAP,138,0,0,Normal,116,N,0.2,Up,0\n52,M,NAP,128,0,0,ST,180,N,3,Up,1\n69,M,ASY,130,0,1,ST,129,N,1,Flat,1\n51,M,ASY,128,0,1,ST,125,Y,1.2,Flat,1\n60,M,ASY,130,186,1,ST,140,Y,0.5,Flat,1\n56,M,ASY,120,100,0,Normal,120,Y,1.5,Flat,1\n55,M,NAP,136,228,0,ST,124,Y,1.6,Flat,1\n54,M,ASY,130,0,0,ST,117,Y,1.4,Flat,1\n77,M,ASY,124,171,0,ST,110,Y,2,Up,1\n63,M,ASY,160,230,1,Normal,105,Y,1,Flat,1\n55,M,NAP,0,0,0,Normal,155,N,1.5,Flat,1\n52,M,NAP,122,0,0,Normal,110,Y,2,Down,1\n64,M,ASY,144,0,0,ST,122,Y,1,Flat,1\n60,M,ASY,140,281,0,ST,118,Y,1.5,Flat,1\n60,M,ASY,120,0,0,Normal,133,Y,2,Up,0\n58,M,ASY,136,203,1,Normal,123,Y,1.2,Flat,1\n59,M,ASY,154,0,0,ST,131,Y,1.5,Up,0\n61,M,NAP,120,0,0,Normal,80,Y,0,Flat,1\n40,M,ASY,125,0,1,Normal,165,N,0,Flat,1\n61,M,ASY,134,0,1,ST,86,N,1.5,Flat,1\n41,M,ASY,104,0,0,ST,111,N,0,Up,0\n57,M,ASY,139,277,1,ST,118,Y,1.9,Flat,1\n63,M,ASY,136,0,0,Normal,84,Y,0,Flat,1\n59,M,ASY,122,233,0,Normal,117,Y,1.3,Down,1\n51,M,ASY,128,0,0,Normal,107,N,0,Up,0\n59,M,NAP,131,0,0,Normal,128,Y,2,Down,1\n42,M,NAP,134,240,0,Normal,160,N,0,Up,0\n55,M,NAP,120,0,0,ST,125,Y,2.5,Flat,1\n63,F,ATA,132,0,0,Normal,130,N,0.1,Up,0\n62,M,ASY,152,153,0,ST,97,Y,1.6,Up,1\n56,M,ATA,124,224,1,Normal,161,N,2,Flat,0\n53,M,ASY,126,0,0,Normal,106,N,0,Flat,1\n68,M,ASY,138,0,0,Normal,130,Y,3,Flat,1\n53,M,ASY,154,0,1,ST,140,Y,1.5,Flat,1\n60,M,NAP,141,316,1,ST,122,Y,1.7,Flat,1\n62,M,ATA,131,0,0,Normal,130,N,0.1,Up,0\n59,M,ASY,178,0,1,LVH,120,Y,0,Flat,1\n51,M,ASY,132,218,1,LVH,139,N,0.1,Up,0\n61,M,ASY,110,0,1,Normal,108,Y,2,Down,1\n57,M,ASY,130,311,1,ST,148,Y,2,Flat,1\n56,M,NAP,170,0,0,LVH,123,Y,2.5,Flat,1\n58,M,ATA,126,0,1,Normal,110,Y,2,Flat,1\n69,M,NAP,140,0,1,ST,118,N,2.5,Down,1\n67,M,TA,142,270,1,Normal,125,N,2.5,Up,1\n58,M,ASY,120,0,0,LVH,106,Y,1.5,Down,1\n65,M,ASY,134,0,0,Normal,112,Y,1.1,Flat,1\n63,M,ATA,139,217,1,ST,128,Y,1.2,Flat,1\n55,M,ATA,110,214,1,ST,180,N,0.4,Up,0\n57,M,ASY,140,214,0,ST,144,Y,2,Flat,1\n65,M,TA,140,252,0,Normal,135,N,0.3,Up,0\n54,M,ASY,136,220,0,Normal,140,Y,3,Flat,1\n72,M,NAP,120,214,0,Normal,102,Y,1,Flat,1\n75,M,ASY,170,203,1,ST,108,N,0,Flat,1\n49,M,TA,130,0,0,ST,145,N,3,Flat,1\n51,M,NAP,137,339,0,Normal,127,Y,1.7,Flat,1\n60,M,ASY,142,216,0,Normal,110,Y,2.5,Flat,1\n64,F,ASY,142,276,0,Normal,140,Y,1,Flat,1\n58,M,ASY,132,458,1,Normal,69,N,1,Down,0\n61,M,ASY,146,241,0,Normal,148,Y,3,Down,1\n67,M,ASY,160,384,1,ST,130,Y,0,Flat,1\n62,M,ASY,135,297,0,Normal,130,Y,1,Flat,1\n65,M,ASY,136,248,0,Normal,140,Y,

In [ ]:
df = pd.read_csv("/content/heart.csv")

df.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0

In [ ]:
df.describe().T

              count        mean         std   min     25%    50%    75%    max
Age           918.0   53.510893    9.432617  28.0   47.00   54.0   60.0   77.0
RestingBP     918.0  132.396514   18.514154   0.0  120.00  130.0  140.0  200.0
Cholesterol   918.0  198.799564  109.384145   0.0  173.25  223.0  267.0  603.0
FastingBS     918.0    0.233115    0.423046   0.0    0.00    0.0    0.0    1.0
MaxHR         918.0  136.809368   25.460334  60.0  120.00  138.0  156.0  202.0
Oldpeak       918.0    0.887364    1.066570  -2.6    0.00    0.6    1.5    6.2
HeartDisease  918.0    0.553377    0.497414   0.0    0.00    1.0    1.0    1.0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Age             918 non-null    int64
 1   Sex             918 non-null    object
 2   ChestPainType   918 non-null    object
 3   RestingBP       918 non-null    int64
 4   Cholesterol     918 non-null    int64
 5   FastingBS       918 non-null    int64
 6   RestingECG      918 non-null    object
 7   MaxHR           918 non-null    int64
 8   ExerciseAngina  918 non-null    object
 9   Oldpeak         918 non-null    float64
 10  ST_Slope        918 non-null    object
 11  HeartDisease    918 non-null    int64
dtypes: float64(1), int64(6), object(5)
memory usage: 86.2+ KB

After some eda, we will move to the Pipeline. Here we skipped the detailed EDA for this dataset.

---

Now in One code cell we will create a pipeline, because if we create different cells, some cells can be forgotten to run, leading the model to unwanted result.

In [ ]:
#First lets import necessary libraries for the pipelines
from sklearn.compose import ColumnTransformer # to combine num and cat features
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.linear_model import LogisticRegression

#Define you target here.
target = "HeartDisease"


cat_LE =[]
cat_OH = []
num_cols_bin = []
num_cols = []

for col in df.columns:
  if df[col].dtype == 'object':
    if len(df[col].unique()) <= 2:
      cat_LE.append(col)
    else:
      cat_OH.append(col)
  elif(col != target):
    if len(df[col].unique()) > 2:
      num_cols.append(col)
    else:
      num_cols_bin.append(col)

print(f"Numerical Columns: {num_cols}")
print(f"Binary Numerical Columns: {num_cols_bin}")
print(f"Label Encoding Columns: {cat_LE}")
print(f"One Hot Encoding Columns: {cat_OH}")

#Now For Numerical PipeLine
num_pipeline = Pipeline([
    ("scaler", StandardScaler())
])

#For Catagorical Pipeline
cat_pipeline = Pipeline([
    ("ohe", OneHotEncoder(drop="first"))
])

#Combine both
preprocess = ColumnTransformer([
    ("num", num_pipeline, num_features),
    ("cat", cat_pipeline, cat_features)
])

#Full pipeline with a simple model
clf = Pipeline([
    ("prep", preprocess),
    ("model", LogisticRegression(max_iter= 1000))
])

catagorical Features: ['Sex', 'ChestPainType', 'RestingECG', 'ExerciseAngina', 'ST_Slope']
Numerical Features: ['Age', 'RestingBP', 'Cholesterol', 'FastingBS', 'MaxHR', 'Oldpeak']

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
df.shape

(918, 12)

#Quick Sanity check with simple Model

In [ ]:
#Train-Test Split

X = df.drop(columns= ["HeartDisease"])
y = df['HeartDisease']

X_train, X_test,y_train, y_test = train_test_split(
    X,y, test_size= 0.25, random_state= 42
)
print(f"train size = {X_train.shape}, \t test size = {X_test.shape}")

#Fit the full pipeline

clf.fit(X_train, y_train)

#Predict and evaluate

from sklearn.metrics import accuracy_score

y_pred = clf.predict(X_test)
acc = accuracy_score(y_test, y_pred)
print("Logistic Regression with prepocessing pipeline: ", acc)

train size = (688, 11), 	 test size = (230, 11)
Logistic Regression with prepocessing pipeline:  0.8652173913043478